# Generated by Django 4.2.2 on 2023-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment',
            field=models.BooleanField(default=False),
        ),
    ]
